// lib/main.dart
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

// If you replaced the placeholder with the actual firebase_options.dart generated
// by `flutterfire configure`, import the options below and pass them to Firebase.initializeApp()
// import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // If you have firebase_options.dart generated by FlutterFire:
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // If you don't have firebase_options.dart yet (placeholder), initialize with default:
  await Firebase.initializeApp();

  runApp(const SafetyApp());
}

class SafetyApp extends StatelessWidget {
  const SafetyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "SafeLink — Digital Safety Toolkit",
      theme: ThemeData(
        primarySwatch: Colors.purple,
        brightness: Brightness.light,
        scaffoldBackgroundColor: Colors.grey[100],
      ),
      home: const InitWrapper(),
      debugShowCheckedModeBanner: false,
    );
  }
}

/// Ensures anonymous sign-in before showing the app
class InitWrapper extends StatefulWidget {
  const InitWrapper({super.key});
  @override
  State<InitWrapper> createState() => _InitWrapperState();
}

class _InitWrapperState extends State<InitWrapper> {
  bool _busy = true;
  @override
  void initState() {
    super.initState();
    _initAuth();
  }

  Future<void> _initAuth() async {
    try {
      final auth = FirebaseAuth.instance;
      if (auth.currentUser == null) {
        await auth.signInAnonymously();
      }
    } catch (e) {
      // silent fallback — app still works using local storage
      debugPrint('Auth init error: $e');
    } finally {
      setState(() => _busy = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_busy) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }
    return const WelcomeScreen();
  }
}

// ---------------- WelcomeScreen ----------------
class WelcomeScreen extends StatelessWidget {
  const WelcomeScreen({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(32.0),
          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
            Icon(Icons.shield, size: 120, color: Colors.purple[700]),
            const SizedBox(height: 20),
            const Text("SafeLink — Digital Safety Toolkit",
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
            const SizedBox(height: 10),
            const Text(
              "A privacy-focused app built for PowerHacks 2025 to protect women & girls online.",
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 30),
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.purple,
                padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 14),
              ),
              onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const HomePage())),
              child: const Text("Get Started"),
            )
          ]),
        ),
      ),
    );
  }
}

// ---------------- HomePage ----------------
class HomePage extends StatelessWidget {
  const HomePage({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("SafeLink"), backgroundColor: Colors.purple),
      body: GridView.count(
        padding: const EdgeInsets.all(20),
        crossAxisCount: 2,
        children: [
          featureButton(context, icon: Icons.info, text: "Safety Tips", screen: const SafetyTipsScreen()),
          featureButton(context, icon: Icons.report, text: "Report Incident", screen: const IncidentReportScreen()),
          featureButton(context, icon: Icons.sos, text: "SOS Emergency", screen: const SosScreen()),
          featureButton(context, icon: Icons.lock, text: "Protection Guides", screen: const ProtectionGuides()),
        ],
      ),
    );
  }
}

Widget featureButton(BuildContext context, {required IconData icon, required String text, required Widget screen}) {
  return Card(
    elevation: 3,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
    child: InkWell(
      borderRadius: BorderRadius.circular(12),
      onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => screen)),
      child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
        Icon(icon, size: 48, color: Colors.purple),
        const SizedBox(height: 8),
        Text(text, textAlign: TextAlign.center),
      ]),
    ),
  );
}

// ---------------- Safety Tips ----------------
class SafetyTipsScreen extends StatelessWidget {
  const SafetyTipsScreen({super.key});
  final List<String> tips = const [
    "Do not share personal photos with strangers.",
    "Use strong passwords and enable 2FA.",
    "Block and report threatening accounts.",
    "Avoid clicking unknown links.",
    "Document evidence of online harassment.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Safety Tips"), backgroundColor: Colors.purple),
      body: ListView.builder(
        padding: const EdgeInsets.all(16),
        itemCount: tips.length,
        itemBuilder: (context, i) => Card(child: ListTile(leading: const Icon(Icons.check_circle, color: Colors.green), title: Text(tips[i]))),
      ),
    );
  }
}

// ---------------- Incident Report (Firestore + Local fallback) ----------------
class IncidentReportScreen extends StatefulWidget {
  const IncidentReportScreen({super.key});
  @override
  State<IncidentReportScreen> createState() => _IncidentReportScreenState();
}

class _IncidentReportScreenState extends State<IncidentReportScreen> {
  final TextEditingController titleController = TextEditingController();
  final TextEditingController descController = TextEditingController();
  final TextEditingController locationController = TextEditingController();
  bool _saving = false;
  String? _localFallback;

  @override
  void initState() {
    super.initState();
    _loadLocal();
  }

  Future<void> _loadLocal() async {
    final prefs = await SharedPreferences.getInstance();
    setState(() => _localFallback = prefs.getString('incident_report'));
  }

  Future<void> _saveToFirestore(String title, String description, String location) async {
    final user = FirebaseAuth.instance.currentUser;
    final uid = user?.uid ?? 'anonymous';
    final doc = {
      'title': title,
      'description': description,
      'location': location,
      'uid': uid,
      'createdAt': FieldValue.serverTimestamp(),
    };
    await FirebaseFirestore.instance.collection('reports').add(doc);
  }

  Future<void> _save() async {
    final title = titleController.text.trim();
    final desc = descController.text.trim();
    final location = locationController.text.trim();

    if (desc.length < 6) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Please enter more details.")));
      return;
    }

    setState(() => _saving = true);
    try {
      await _saveToFirestore(title, desc, location);
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('incident_report', desc);
      setState(() => _localFallback = desc);
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Report saved to cloud.")));
      titleController.clear();
      descController.clear();
      locationController.clear();
    } catch (e) {
      // fallback
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('incident_report', desc);
      setState(() => _localFallback = desc);
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Saved locally (offline).")));
    } finally {
      setState(() => _saving = false);
    }
  }

  Stream<QuerySnapshot<Map<String, dynamic>>> _userStream() {
    final uid = FirebaseAuth.instance.currentUser?.uid ?? 'anonymous';
    return FirebaseFirestore.instance
        .collection('reports')
        .where('uid', isEqualTo: uid)
        .orderBy('createdAt', descending: true)
        .limit(50)
        .snapshots();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Report Incident"), backgroundColor: Colors.purple),
      body: Padding(
        padding: const EdgeInsets.all(14),
        child: Column(children: [
          const Text("Describe what happened. Reports are saved to Firestore (or locally if offline)."),
          const SizedBox(height: 8),
          TextField(controller: titleController, decoration: const InputDecoration(labelText: 'Title (optional)')),
          const SizedBox(height: 8),
          TextField(controller: descController, maxLines: 4, decoration: const InputDecoration(border: OutlineInputBorder(), hintText: 'Enter details...')),
          const SizedBox(height: 8),
          TextField(controller: locationController, decoration: const InputDecoration(labelText: 'Location (optional)')),
          const SizedBox(height: 12),
          ElevatedButton(
            onPressed: _saving ? null : _save,
            style: ElevatedButton.styleFrom(backgroundColor: Colors.purple),
            child: _saving ? const SizedBox(height: 18, width: 18, child: CircularProgressIndicator(strokeWidth: 2)) : const Text("Save Report"),
          ),
          const SizedBox(height: 12),
          Expanded(
            child: StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
              stream: _userStream(),
              builder: (context, snap) {
                if (snap.connectionState == ConnectionState.waiting) return const Center(child: CircularProgressIndicator());
                if (snap.hasError) return Center(child: Text('Error: ${snap.error}'));
                final docs = snap.data?.docs ?? [];
                if (docs.isEmpty) {
                  return _localFallback == null ? const Center(child: Text('No reports yet.')) : Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Saved locally:', style: TextStyle(fontWeight: FontWeight.bold)), const SizedBox(height: 8), Text(_localFallback!)]);
                }
                return ListView.builder(
                  itemCount: docs.length,
                  itemBuilder: (context, i) {
                    final d = docs[i].data();
                    final ts = d['createdAt'] as Timestamp?;
                    final dateStr = ts?.toDate().toLocal().toString().split('.').first ?? '—';
                    return Card(
                      child: ListTile(
                        title: Text(d['title'] ?? '(no title)'),
                        subtitle: Text('$dateStr\n${d['description'] ?? ''}\n${(d['location'] ?? '').isEmpty ? '' : 'Location: ${d['location']}'}'),
                        isThreeLine: true,
                      ),
                    );
                  },
                );
              },
            ),
          )
        ]),
      ),
    );
  }
}

// ---------------- SOS ----------------
class SosScreen extends StatelessWidget {
  const SosScreen({super.key});
  Future<void> _call(String number) async {
    final Uri url = Uri(scheme: 'tel', path: number);
    await launchUrl(url);
  }

  @override
  Widget build(BuildContext context) {
    final numbers = ['911', '112', '999', '833'];
    return Scaffold(
      appBar: AppBar(title: const Text("SOS Emergency"), backgroundColor: Colors.purple),
      body: ListView(padding: const EdgeInsets.all(12), children: numbers.map((n) => Card(child: ListTile(leading: const Icon(Icons.phone, color: Colors.red), title: Text('Call $n'), onTap: () => _call(n)))).toList()),
    );
  }
}

// ---------------- Protection Guides ----------------
class ProtectionGuides extends StatelessWidget {
  const ProtectionGuides({super.key});
  final List<String> guides = const [
    "How to protect your Facebook account",
    "How to protect your TikTok account",
    "How to secure your Instagram",
    "How to avoid digital stalking",
    "How to report cyberbullying",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Protection Guides"), backgroundColor: Colors.purple),
      body: ListView.builder(padding: const EdgeInsets.all(12), itemCount: guides.length, itemBuilder: (c, i) => Card(child: ListTile(leading: const Icon(Icons.lock, color: Colors.blue), title: Text(guides[i])))),
    );
  }
}